<h1>Activity 1 - PALMER PENGUIN DATA ANALYTICS PROJECT</h1>
<hr>
<h3>Analyst : Nerjie Angelo Mecantina</h3>

In [1]:
#import Libraries

import pandas as pd
import numpy as np

<h2>Converting Dataset(s) into Dataframe</h2>

<h3>Requirements</h3>
<ul>
    <li>Name of the Dataframes</li>
    <li>Filepath</li>
</ul>

In [2]:
penguins = pd.read_csv('datasets\\penguins.csv')

In [3]:
penguins

rowid    species     island  bill_length_mm  bill_depth_mm  \
0        1     Adelie  Torgersen            39.1           18.7   
1        2     Adelie  Torgersen            39.5           17.4   
2        3     Adelie  Torgersen            40.3           18.0   
3        4     Adelie  Torgersen             NaN            NaN   
4        5     Adelie  Torgersen            36.7           19.3   
..     ...        ...        ...             ...            ...   
339    340  Chinstrap      Dream            55.8           19.8   
340    341  Chinstrap      Dream            43.5           18.1   
341    342  Chinstrap      Dream            49.6           18.2   
342    343  Chinstrap      Dream            50.8           19.0   
343    344  Chinstrap      Dream            50.2           18.7   

     flipper_length_mm  body_mass_g     sex  year  
0                181.0       3750.0    male  2007  
1                186.0       3800.0  female  2007  
2                195.0       3250.0  female  2007  
3                  NaN          NaN     NaN  2007  
4                193.0       3450.0  female  2007  
..                 ...          ...     ...   ...  
339              207.0       4000.0    male  2009  
340              202.0       3400.0  female  2009  
341              193.0       3775.0    male  2009  
342              210.0       4100.0    male  2009  
343              198.0       3775.0  female  2009  

[344 rows x 9 columns]

<h2>Descriptive Analysis</h2>

In [4]:
penguins.describe()

rowid  bill_length_mm  bill_depth_mm  flipper_length_mm  \
count  344.000000      342.000000     342.000000         342.000000   
mean   172.500000       43.921930      17.151170         200.915205   
std     99.448479        5.459584       1.974793          14.061714   
min      1.000000       32.100000      13.100000         172.000000   
25%     86.750000       39.225000      15.600000         190.000000   
50%    172.500000       44.450000      17.300000         197.000000   
75%    258.250000       48.500000      18.700000         213.000000   
max    344.000000       59.600000      21.500000         231.000000   

       body_mass_g         year  
count   342.000000   344.000000  
mean   4201.754386  2008.029070  
std     801.954536     0.818356  
min    2700.000000  2007.000000  
25%    3550.000000  2007.000000  
50%    4050.000000  2008.000000  
75%    4750.000000  2009.000000  
max    6300.000000  2009.000000

In [5]:
penguins.describe().T

count         mean         std     min       25%      50%  \
rowid              344.0   172.500000   99.448479     1.0    86.750   172.50   
bill_length_mm     342.0    43.921930    5.459584    32.1    39.225    44.45   
bill_depth_mm      342.0    17.151170    1.974793    13.1    15.600    17.30   
flipper_length_mm  342.0   200.915205   14.061714   172.0   190.000   197.00   
body_mass_g        342.0  4201.754386  801.954536  2700.0  3550.000  4050.00   
year               344.0  2008.029070    0.818356  2007.0  2007.000  2008.00   

                       75%     max  
rowid               258.25   344.0  
bill_length_mm       48.50    59.6  
bill_depth_mm        18.70    21.5  
flipper_length_mm   213.00   231.0  
body_mass_g        4750.00  6300.0  
year               2009.00  2009.0

<h2>Checking Null Values</h2>

In [6]:
penguins.isnull()

rowid  species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    False    False   False           False          False              False   
1    False    False   False           False          False              False   
2    False    False   False           False          False              False   
3    False    False   False            True           True               True   
4    False    False   False           False          False              False   
..     ...      ...     ...             ...            ...                ...   
339  False    False   False           False          False              False   
340  False    False   False           False          False              False   
341  False    False   False           False          False              False   
342  False    False   False           False          False              False   
343  False    False   False           False          False              False   

     body_mass_g    sex   year  
0          False  False  False  
1          False  False  False  
2          False  False  False  
3           True   True  False  
4          False  False  False  
..           ...    ...    ...  
339        False  False  False  
340        False  False  False  
341        False  False  False  
342        False  False  False  
343        False  False  False  

[344 rows x 9 columns]

In [7]:
penguins.isnull().sum()

rowid                 0
species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
dtype: int64

<h2>Filtering a column</h2>

In [8]:
penguins['species']

0         Adelie
1         Adelie
2         Adelie
3         Adelie
4         Adelie
         ...    
339    Chinstrap
340    Chinstrap
341    Chinstrap
342    Chinstrap
343    Chinstrap
Name: species, Length: 344, dtype: object

In [9]:
penguins['species'].value_counts()

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

In [14]:
penguins[penguins['species'] == 'Adelie']

rowid species     island  bill_length_mm  bill_depth_mm  \
0        1  Adelie  Torgersen            39.1           18.7   
1        2  Adelie  Torgersen            39.5           17.4   
2        3  Adelie  Torgersen            40.3           18.0   
3        4  Adelie  Torgersen             NaN            NaN   
4        5  Adelie  Torgersen            36.7           19.3   
..     ...     ...        ...             ...            ...   
147    148  Adelie      Dream            36.6           18.4   
148    149  Adelie      Dream            36.0           17.8   
149    150  Adelie      Dream            37.8           18.1   
150    151  Adelie      Dream            36.0           17.1   
151    152  Adelie      Dream            41.5           18.5   

     flipper_length_mm  body_mass_g     sex  year  
0                181.0       3750.0    male  2007  
1                186.0       3800.0  female  2007  
2                195.0       3250.0  female  2007  
3                  NaN          NaN     NaN  2007  
4                193.0       3450.0  female  2007  
..                 ...          ...     ...   ...  
147              184.0       3475.0  female  2009  
148              195.0       3450.0  female  2009  
149              193.0       3750.0    male  2009  
150              187.0       3700.0  female  2009  
151              201.0       4000.0    male  2009  

[152 rows x 9 columns]

In [15]:
penguins[penguins['species'] != 'Adelie']

rowid    species  island  bill_length_mm  bill_depth_mm  \
152    153     Gentoo  Biscoe            46.1           13.2   
153    154     Gentoo  Biscoe            50.0           16.3   
154    155     Gentoo  Biscoe            48.7           14.1   
155    156     Gentoo  Biscoe            50.0           15.2   
156    157     Gentoo  Biscoe            47.6           14.5   
..     ...        ...     ...             ...            ...   
339    340  Chinstrap   Dream            55.8           19.8   
340    341  Chinstrap   Dream            43.5           18.1   
341    342  Chinstrap   Dream            49.6           18.2   
342    343  Chinstrap   Dream            50.8           19.0   
343    344  Chinstrap   Dream            50.2           18.7   

     flipper_length_mm  body_mass_g     sex  year  
152              211.0       4500.0  female  2007  
153              230.0       5700.0    male  2007  
154              210.0       4450.0  female  2007  
155              218.0       5700.0    male  2007  
156              215.0       5400.0    male  2007  
..                 ...          ...     ...   ...  
339              207.0       4000.0    male  2009  
340              202.0       3400.0  female  2009  
341              193.0       3775.0    male  2009  
342              210.0       4100.0    male  2009  
343              198.0       3775.0  female  2009  

[192 rows x 9 columns]

In [16]:
Adelie_df = penguins[penguins['species'] == 'Adelie']

In [17]:
Adelie_df 

rowid species     island  bill_length_mm  bill_depth_mm  \
0        1  Adelie  Torgersen            39.1           18.7   
1        2  Adelie  Torgersen            39.5           17.4   
2        3  Adelie  Torgersen            40.3           18.0   
3        4  Adelie  Torgersen             NaN            NaN   
4        5  Adelie  Torgersen            36.7           19.3   
..     ...     ...        ...             ...            ...   
147    148  Adelie      Dream            36.6           18.4   
148    149  Adelie      Dream            36.0           17.8   
149    150  Adelie      Dream            37.8           18.1   
150    151  Adelie      Dream            36.0           17.1   
151    152  Adelie      Dream            41.5           18.5   

     flipper_length_mm  body_mass_g     sex  year  
0                181.0       3750.0    male  2007  
1                186.0       3800.0  female  2007  
2                195.0       3250.0  female  2007  
3                  NaN          NaN     NaN  2007  
4                193.0       3450.0  female  2007  
..                 ...          ...     ...   ...  
147              184.0       3475.0  female  2009  
148              195.0       3450.0  female  2009  
149              193.0       3750.0    male  2009  
150              187.0       3700.0  female  2009  
151              201.0       4000.0    male  2009  

[152 rows x 9 columns]

In [18]:
Gentoo_df = penguins[penguins['species'] == 'Gentoo']

In [19]:
Gentoo_df

rowid species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
152    153  Gentoo  Biscoe            46.1           13.2              211.0   
153    154  Gentoo  Biscoe            50.0           16.3              230.0   
154    155  Gentoo  Biscoe            48.7           14.1              210.0   
155    156  Gentoo  Biscoe            50.0           15.2              218.0   
156    157  Gentoo  Biscoe            47.6           14.5              215.0   
..     ...     ...     ...             ...            ...                ...   
271    272  Gentoo  Biscoe             NaN            NaN                NaN   
272    273  Gentoo  Biscoe            46.8           14.3              215.0   
273    274  Gentoo  Biscoe            50.4           15.7              222.0   
274    275  Gentoo  Biscoe            45.2           14.8              212.0   
275    276  Gentoo  Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  year  
152       4500.0  female  2007  
153       5700.0    male  2007  
154       4450.0  female  2007  
155       5700.0    male  2007  
156       5400.0    male  2007  
..           ...     ...   ...  
271          NaN     NaN  2009  
272       4850.0  female  2009  
273       5750.0    male  2009  
274       5200.0  female  2009  
275       5400.0    male  2009  

[124 rows x 9 columns]

In [20]:
Chinstrap_df = penguins[penguins['species'] == 'Chinstrap']

In [21]:
Chinstrap_df

rowid    species island  bill_length_mm  bill_depth_mm  \
276    277  Chinstrap  Dream            46.5           17.9   
277    278  Chinstrap  Dream            50.0           19.5   
278    279  Chinstrap  Dream            51.3           19.2   
279    280  Chinstrap  Dream            45.4           18.7   
280    281  Chinstrap  Dream            52.7           19.8   
..     ...        ...    ...             ...            ...   
339    340  Chinstrap  Dream            55.8           19.8   
340    341  Chinstrap  Dream            43.5           18.1   
341    342  Chinstrap  Dream            49.6           18.2   
342    343  Chinstrap  Dream            50.8           19.0   
343    344  Chinstrap  Dream            50.2           18.7   

     flipper_length_mm  body_mass_g     sex  year  
276              192.0       3500.0  female  2007  
277              196.0       3900.0    male  2007  
278              193.0       3650.0    male  2007  
279              188.0       3525.0  female  2007  
280              197.0       3725.0    male  2007  
..                 ...          ...     ...   ...  
339              207.0       4000.0    male  2009  
340              202.0       3400.0  female  2009  
341              193.0       3775.0    male  2009  
342              210.0       4100.0    male  2009  
343              198.0       3775.0  female  2009  

[68 rows x 9 columns]

In [22]:
penguins[penguins['body_mass_g'] >= 4000]

rowid    species     island  bill_length_mm  bill_depth_mm  \
7        8     Adelie  Torgersen            39.2           19.6   
9       10     Adelie  Torgersen            42.0           20.2   
14      15     Adelie  Torgersen            34.6           21.1   
17      18     Adelie  Torgersen            42.5           20.7   
19      20     Adelie  Torgersen            46.0           21.5   
..     ...        ...        ...             ...            ...   
323    324  Chinstrap      Dream            49.0           19.6   
329    330  Chinstrap      Dream            50.7           19.7   
333    334  Chinstrap      Dream            49.3           19.9   
339    340  Chinstrap      Dream            55.8           19.8   
342    343  Chinstrap      Dream            50.8           19.0   

     flipper_length_mm  body_mass_g   sex  year  
7                195.0       4675.0  male  2007  
9                190.0       4250.0   NaN  2007  
14               198.0       4400.0  male  2007  
17               197.0       4500.0  male  2007  
19               194.0       4200.0  male  2007  
..                 ...          ...   ...   ...  
323              212.0       4300.0  male  2009  
329              203.0       4050.0  male  2009  
333              203.0       4050.0  male  2009  
339              207.0       4000.0  male  2009  
342              210.0       4100.0  male  2009  

[177 rows x 9 columns]

In [23]:
penguins[(penguins['species']== 'Chinstrap') & (penguins['body_mass_g'] >= 4000)]

rowid    species island  bill_length_mm  bill_depth_mm  \
284    285  Chinstrap  Dream            46.0           18.9   
289    290  Chinstrap  Dream            52.0           18.1   
291    292  Chinstrap  Dream            50.5           19.6   
295    296  Chinstrap  Dream            49.2           18.2   
301    302  Chinstrap  Dream            52.0           19.0   
305    306  Chinstrap  Dream            52.8           20.0   
307    308  Chinstrap  Dream            54.2           20.8   
309    310  Chinstrap  Dream            51.0           18.8   
313    314  Chinstrap  Dream            52.0           20.7   
315    316  Chinstrap  Dream            53.5           19.9   
321    322  Chinstrap  Dream            50.8           18.5   
323    324  Chinstrap  Dream            49.0           19.6   
329    330  Chinstrap  Dream            50.7           19.7   
333    334  Chinstrap  Dream            49.3           19.9   
339    340  Chinstrap  Dream            55.8           19.8   
342    343  Chinstrap  Dream            50.8           19.0   

     flipper_length_mm  body_mass_g     sex  year  
284              195.0       4150.0  female  2007  
289              201.0       4050.0    male  2007  
291              201.0       4050.0    male  2007  
295              195.0       4400.0    male  2007  
301              197.0       4150.0    male  2007  
305              205.0       4550.0    male  2008  
307              201.0       4300.0    male  2008  
309              203.0       4100.0    male  2008  
313              210.0       4800.0    male  2008  
315              205.0       4500.0    male  2008  
321              201.0       4450.0    male  2009  
323              212.0       4300.0    male  2009  
329              203.0       4050.0    male  2009  
333              203.0       4050.0    male  2009  
339              207.0       4000.0    male  2009  
342              210.0       4100.0    male  2009

<h2>FILLING UP NULL VALUES</h2>

In [24]:
penguins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   rowid              344 non-null    int64  
 1   species            344 non-null    object 
 2   island             344 non-null    object 
 3   bill_length_mm     342 non-null    float64
 4   bill_depth_mm      342 non-null    float64
 5   flipper_length_mm  342 non-null    float64
 6   body_mass_g        342 non-null    float64
 7   sex                333 non-null    object 
 8   year               344 non-null    int64  
dtypes: float64(4), int64(2), object(3)
memory usage: 24.3+ KB


In [25]:
penguins.isnull().sum()

rowid                 0
species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
dtype: int64

In [26]:
penguins['bill_depth_mm'] = penguins['bill_depth_mm'].fillna(penguins['bill_depth_mm'].mean())

In [27]:
penguins.isnull().sum()

rowid                 0
species               0
island                0
bill_length_mm        2
bill_depth_mm         0
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
dtype: int64

In [28]:
penguins['bill_length_mm'] = penguins['bill_length_mm'].fillna(penguins['bill_length_mm'].mean())

In [29]:
penguins.isnull().sum()

rowid                 0
species               0
island                0
bill_length_mm        0
bill_depth_mm         0
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
dtype: int64

In [30]:
penguins['flipper_length_mm'] = penguins['flipper_length_mm'].fillna(penguins['flipper_length_mm'].mean())

In [31]:
penguins.isnull().sum()

rowid                 0
species               0
island                0
bill_length_mm        0
bill_depth_mm         0
flipper_length_mm     0
body_mass_g           2
sex                  11
year                  0
dtype: int64

In [32]:
penguins['body_mass_g'] = penguins['body_mass_g'].fillna(penguins['body_mass_g'].mean())

In [33]:
penguins.isnull().sum()

rowid                 0
species               0
island                0
bill_length_mm        0
bill_depth_mm         0
flipper_length_mm     0
body_mass_g           0
sex                  11
year                  0
dtype: int64

In [34]:
penguins['sex'].mode()

0    male
Name: sex, dtype: object

In [35]:
penguins['sex'] = penguins['sex'].fillna(penguins['sex'].mode()[0])

In [36]:
penguins.isnull().sum()

rowid                0
species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
dtype: int64

<h2>Changing the Data Type</h2>

In [37]:
penguins['species'] = penguins['species'].astype('category')
penguins['year'] = penguins['year'].astype('category')
penguins['sex'] = penguins['sex'].astype('category')
penguins['island'] = penguins['island'].astype('category')

In [38]:
penguins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype   
---  ------             --------------  -----   
 0   rowid              344 non-null    int64   
 1   species            344 non-null    category
 2   island             344 non-null    category
 3   bill_length_mm     344 non-null    float64 
 4   bill_depth_mm      344 non-null    float64 
 5   flipper_length_mm  344 non-null    float64 
 6   body_mass_g        344 non-null    float64 
 7   sex                344 non-null    category
 8   year               344 non-null    category
dtypes: category(4), float64(4), int64(1)
memory usage: 15.4 KB


In [39]:
penguins['mass_kg'] = np.round(penguins['body_mass_g'] / 1000 , 1)

In [40]:
penguins

rowid    species     island  bill_length_mm  bill_depth_mm  \
0        1     Adelie  Torgersen        39.10000       18.70000   
1        2     Adelie  Torgersen        39.50000       17.40000   
2        3     Adelie  Torgersen        40.30000       18.00000   
3        4     Adelie  Torgersen        43.92193       17.15117   
4        5     Adelie  Torgersen        36.70000       19.30000   
..     ...        ...        ...             ...            ...   
339    340  Chinstrap      Dream        55.80000       19.80000   
340    341  Chinstrap      Dream        43.50000       18.10000   
341    342  Chinstrap      Dream        49.60000       18.20000   
342    343  Chinstrap      Dream        50.80000       19.00000   
343    344  Chinstrap      Dream        50.20000       18.70000   

     flipper_length_mm  body_mass_g     sex  year  mass_kg  
0           181.000000  3750.000000    male  2007      3.8  
1           186.000000  3800.000000  female  2007      3.8  
2           195.000000  3250.000000  female  2007      3.2  
3           200.915205  4201.754386    male  2007      4.2  
4           193.000000  3450.000000  female  2007      3.4  
..                 ...          ...     ...   ...      ...  
339         207.000000  4000.000000    male  2009      4.0  
340         202.000000  3400.000000  female  2009      3.4  
341         193.000000  3775.000000    male  2009      3.8  
342         210.000000  4100.000000    male  2009      4.1  
343         198.000000  3775.000000  female  2009      3.8  

[344 rows x 10 columns]

In [41]:
penguins.columns

Index(['rowid', 'species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex', 'year', 'mass_kg'],
      dtype='object')

In [42]:
penguins['mass_kg'].min()

np.float64(2.7)

In [43]:
penguins['mass_kg'].max()

np.float64(6.3)

In [44]:
penguins[penguins['mass_kg'] == 6.3]

rowid species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
169    170  Gentoo  Biscoe            49.2           15.2              221.0   

     body_mass_g   sex  year  mass_kg  
169       6300.0  male  2007      6.3

In [45]:
penguins['mass_kg'].mean()

np.float64(4.2020348837209305)

In [46]:

penguins[penguins['mass_kg'] == 4]

rowid    species     island  bill_length_mm  bill_depth_mm  \
23      24     Adelie     Biscoe            38.2           18.1   
29      30     Adelie     Biscoe            40.5           18.9   
36      37     Adelie      Dream            38.8           20.0   
53      54     Adelie     Biscoe            42.0           19.5   
63      64     Adelie     Biscoe            41.1           18.2   
65      66     Adelie     Biscoe            41.6           18.0   
79      80     Adelie  Torgersen            42.1           19.1   
88      89     Adelie      Dream            38.3           19.2   
125    126     Adelie  Torgersen            40.6           19.0   
129    130     Adelie  Torgersen            44.1           18.0   
137    138     Adelie      Dream            40.2           20.1   
151    152     Adelie      Dream            41.5           18.5   
192    193     Gentoo     Biscoe            42.7           13.7   
281    282  Chinstrap      Dream            45.2           17.8   
289    290  Chinstrap      Dream            52.0           18.1   
291    292  Chinstrap      Dream            50.5           19.6   
316    317  Chinstrap      Dream            49.0           19.5   
327    328  Chinstrap      Dream            51.4           19.0   
329    330  Chinstrap      Dream            50.7           19.7   
333    334  Chinstrap      Dream            49.3           19.9   
336    337  Chinstrap      Dream            51.9           19.5   
339    340  Chinstrap      Dream            55.8           19.8   

     flipper_length_mm  body_mass_g     sex  year  mass_kg  
23               185.0       3950.0    male  2007      4.0  
29               180.0       3950.0    male  2007      4.0  
36               190.0       3950.0    male  2007      4.0  
53               200.0       4050.0    male  2008      4.0  
63               192.0       4050.0    male  2008      4.0  
65               192.0       3950.0    male  2008      4.0  
79               195.0       4000.0    male  2008      4.0  
88               189.0       3950.0    male  2008      4.0  
125              199.0       4000.0    male  2009      4.0  
129              210.0       4000.0    male  2009      4.0  
137              200.0       3975.0    male  2009      4.0  
151              201.0       4000.0    male  2009      4.0  
192              208.0       3950.0  female  2008      4.0  
281              198.0       3950.0  female  2007      4.0  
289              201.0       4050.0    male  2007      4.0  
291              201.0       4050.0    male  2007      4.0  
316              210.0       3950.0    male  2008      4.0  
327              201.0       3950.0    male  2009      4.0  
329              203.0       4050.0    male  2009      4.0  
333              203.0       4050.0    male  2009      4.0  
336              206.0       3950.0    male  2009      4.0  
339              207.0       4000.0    male  2009      4.0

<h1>Exploratory Data Analytics</h1>
<hr>

<h2>Question 1</h2>
<h3>What is the average body mass in kg of all penguins?</h3>

In [76]:
np.round(penguins['mass_kg'].mean())

np.float64(4.0)

<h2>Insight:</h2>
<p>Base on the Dataset the average body mass in kg of all penguins is 4.0 kg.</p>

<h2>Question 2</h2>
<h3>How many male and female penguins are in the Biscoe island?</h3>

In [55]:
penguins[penguins['island'] == 'Biscoe']['sex'].value_counts()

sex
male      88
female    80
Name: count, dtype: int64

<h2>Insight:</h2>
<p>There are 88 male and 80 female in the Biscoe island.</p>

<h2>Question 3</h2>
<h3>Which island has the highest number of penguins?</h3>

In [64]:
penguins['island'].value_counts()

island
Biscoe       168
Dream        124
Torgersen     52
Name: count, dtype: int64

<h2>Insight:</h2>
<p>Biscoe island has the hightest number of penguins.</p>

<h2>Question 4</h2>
<h3>What is the average flipper length by species?</h3>

In [67]:
np.round(penguins.groupby('species')['flipper_length_mm'].mean())

C:\Users\This PC\AppData\Local\Temp\ipykernel_12868\606653159.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  np.round(penguins.groupby('species')['flipper_length_mm'].mean())


species
Adelie       190.0
Chinstrap    196.0
Gentoo       217.0
Name: flipper_length_mm, dtype: float64

<h2>Insight:</h2>
<p>Based on the result, the average flipper length of the Gentoo species is 217.0mm.</p>

<h3>Question 5</h3>
<h3> What is the smallest mass_kg recorded?</h3>

In [68]:
penguins['mass_kg'].min()

np.float64(2.7)

<h2>Insight:</h2>
<p>The smallest mass_kg recorded is 2.7kg.</p>

<h2>Question 6</h2>
<h3> What is the average bill length of Adelie for each year?</h3>

In [74]:
np.round(penguins[penguins['species'] == 'Adelie'].groupby('year')['bill_length_mm'].mean())

C:\Users\This PC\AppData\Local\Temp\ipykernel_12868\1260497108.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  np.round(penguins[penguins['species'] == 'Adelie'].groupby('year')['bill_length_mm'].mean())


year
2007    39.0
2008    39.0
2009    39.0
Name: bill_length_mm, dtype: float64

<h2>Insight:</h2>
<p>Based on the result, there are no changes in bill length for each year.</p>

<h2>Question 7</h2>
<h3>What is the average bill depth for male and female penguins?</h3>

In [75]:
np.round(penguins.groupby('sex')['bill_depth_mm'].mean())

C:\Users\This PC\AppData\Local\Temp\ipykernel_12868\3432808965.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  np.round(penguins.groupby('sex')['bill_depth_mm'].mean())


sex
female    16.0
male      18.0
Name: bill_depth_mm, dtype: float64

<h2>Insight:</h2>
<p>Based on the result, the average bill depth of males is 18.0 mm, while females have an average of 16.0 mm.</p>